import {
  Article,
  CalendarCheck,
  ChalkboardTeacher,
  CurrencyDollar,
  Handshake,
  PresentationChart,
  Ticket,
  UserCirclePlus,
  UsersThree,
} from "phosphor-react";
// ==============================|| EXTRA PAGES MENU ITEMS ||============================== //

const pages = {
  id: "pages",
  type: "group",
  children: [
    {
      id: "painel-evento",
      title: "Meu evento",
      type: "item",
      url: "",
      icon: CalendarCheck,
      breadcrumbs: false,
    },
    {
      id: "programacao",
      title: "Programação",
      type: "collapse",
      url: "programacao",
      icon: ChalkboardTeacher,
      breadcrumbs: false,
      children: [
        {
          id: "cursos",
          title: "Cursos",
          type: "item",
          url: "programacao/cursos",
          breadcrumbs: false,
        },
        {
          id: "palestras",
          title: "Palestras",
          type: "item",
          url: "programacao/palestras",
          breadcrumbs: false,
        },
        {
          id: "certificados",
          title: "Certificados",
          type: "item",
          url: "programacao/certificados",
          breadcrumbs: false,
        },
      ],
    },
    {
      id: "ingressos",
      title: "Inscrições",
      type: "item",
      url: "ingressos",
      icon: Ticket,
      breadcrumbs: false,
    },
    {
      id: "participantes",
      title: "Participantes",
      type: "item",
      url: "participantes",
      icon: UsersThree,
      breadcrumbs: false,
    },
    {
      id: "submissoes",
      title: "Submissões",
      type: "collapse",
      url: "submissoes",
      icon: Article,
      breadcrumbs: false,
      children: [
        {
          id: "cursos",
          title: "Cursos",
          type: "item",
          url: "atividades/cursos",
          breadcrumbs: false,
        },
        {
          id: "palestras",
          title: "Palestras",
          type: "item",
          url: "atividades/palestras",
          breadcrumbs: false,
        },
        {
          id: "certificados",
          title: "Certificados",
          type: "item",
          url: "atividades/certificados",
          breadcrumbs: false,
        },
      ],
    },
    {
      id: "voluntarios",
      title: "Equipe de apoio",
      type: "collapse",
      url: "voluntarios",
      icon: UserCirclePlus,
      breadcrumbs: false,
      children: [
        {
          id: "cursos",
          title: "Cursos",
          type: "item",
          url: "atividades/cursos",
          breadcrumbs: false,
        },
        {
          id: "palestras",
          title: "Palestras",
          type: "item",
          url: "atividades/palestras",
          breadcrumbs: false,
        },
        {
          id: "certificados",
          title: "Certificados",
          type: "item",
          url: "atividades/certificados",
          breadcrumbs: false,
        },
      ],
    },
    {
      id: "estatisticas",
      title: "Estatísticas",
      type: "item",
      url: "estatisticas",
      icon: PresentationChart,
      breadcrumbs: false,
    },
    {
      id: "financeiro",
      title: "Financeiro",
      type: "item",
      url: "financeiro",
      icon: CurrencyDollar,
      breadcrumbs: false,
    },
    {
      id: "patrocinadores",
      title: "Patrocinadores",
      type: "item",
      url: "patrocinadores",
      icon: Handshake,
      breadcrumbs: false,
    },
  ],
};

export default pages;
